name: gradle_push

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup Java
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 11
          distribution: 'zulu'
      -
        name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-executable: gradlew
          arguments: :amber-plugin:publishPlugins --stacktrace --no-daemon --continue -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
